name: Check JSON, YAML, and Large Files

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonlint yamllint

      - name: Check JSON files
        run: |
          find . -name "*.json" -print0 | xargs -0 -n 1 jsonlint

      - name: Check YAML files
        run: |
          yamllint .

      - name: Check for added large files
        run: |
          git diff --cached --name-only | while read filename; do
            if [ -f "$filename" ] && [ $(wc -c <"$filename") -gt 500000 ]; then
              echo "Large file detected: $filename ($(wc -c <"$filename") bytes)"
              exit 1
            fi
          done

      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.